import dayjs from 'dayjs'

export const CONFESSIONS = [
	{
		id: '1',
		displayName: 'JohnDoe123',
		gender: 'm',
		age: '25',
		favorite: true,
		dislikes: ['1', '2', '3'],
		likes: ['23', '34', '56'],
		comments: '5',
		confession:
			'I have a fear of clowns. It started when I was a kid and watched a horror movie. Now, even seeing a clown at a party makes me anxious.',
		type: 'fear',
		createdAt: dayjs().toISOString(),
	},
	{
		id: '2',
		displayName: 'JaneDoe456',
		gender: 'f',
		age: '30',
		favorite: false,
		dislikes: ['1', '2', '3'],
		likes: ['42', '34', '56'],
		comments: '10',
		confession: "I love singing in the shower. It's my private concert every morning!",
		type: 'happiness',
		createdAt: dayjs().subtract(1, 'days').toISOString(),
	},
	{
		id: '3',
		displayName: 'MikeSmith789',
		gender: 'm',
		age: '22',
		favorite: true,
		dislikes: ['1', '2', '3'],
		likes: ['15', '34', '56'],
		comments: '2',
		confession:
			"I never learned how to ride a bike. My parents tried, but I just couldn't get the hang of it.",
		type: 'sad',
		createdAt: dayjs().subtract(2, 'days').toISOString(),
	},
	{
		id: '4',
		displayName: 'SaraJones321',
		gender: 'f',
		age: '28',
		favorite: false,
		dislikes: ['1', '2', '3'],
		likes: ['36', '34', '56'],
		comments: '8',
		confession:
			'I am secretly afraid of the dark. Even at this age, I need a night light to sleep peacefully.',
		type: 'fear',
		createdAt: '2024-06-30T2:00:00Z',
	},
	{
		id: '5',
		displayName: 'TomWhite654',
		gender: 'm',
		age: '35',
		favorite: true,
		dislikes: ['1', '2', '3'],
		likes: ['55', '34', '56'],
		comments: '20',
		confession:
			'I often talk to my plants. I believe they grow better when I tell them about my day.',
		type: 'kindness',
		createdAt: '2023-06-18T09:30:00Z',
	},
	{
		id: '6',
		displayName: 'LindaGreen987',
		gender: 'f',
		age: '26',
		favorite: false,
		dislikes: ['1', '2', '3'],
		likes: ['29', '34', '56'],
		comments: '12',
		confession:
			"I can't stand the sound of chewing. It drives me crazy, especially when someone is eating loudly next to me.",
		type: 'just saying',
		createdAt: '2023-06-22T17:20:00Z',
	},
	{
		id: '7',
		displayName: 'ChrisBlue123',
		gender: 'm',
		age: '27',
		favorite: true,
		dislikes: ['1', '2', '3'],
		likes: ['33', '34', '56'],
		comments: '7',
		confession:
			'I still watch cartoons every morning. They remind me of simpler times and make me happy.',
		type: 'funny',
		createdAt: '2023-06-24T14:15:00Z',
	},
	{
		id: '8',
		displayName: 'AnnaYellow456',
		gender: 'f',
		age: '31',
		favorite: true,
		dislikes: ['1', '2', '3'],
		likes: ['48', '34', '56'],
		comments: '15',
		confession:
			'I am terrified of heights. Once, I froze on a Ferris wheel and had to be helped down.',
		type: 'fear',
		createdAt: '2023-06-26T11:45:00Z',
	},
]
