export const APP_NOTIFICATIONS = [
	{
		id: '1',
		title: 'Welcome to Confess!',
		date: '2024-05-01T10:00:00Z',
		body: 'Thank you for joining Confess! Start sharing your thoughts and read confessions from others anonymously.',
		avatar: 'https://example.com/avatars/welcome.png',
	},
	{
		id: '2',
		title: 'New Confession Alert',
		date: '2023-07-01T12:30:00Z',
		body: 'Someone just shared a new confession. Tap here to read it.',
		avatar: 'https://example.com/avatars/new_confession.png',
	},
	{
		id: '3',
		title: 'Comment on Your Confession',
		date: '2024-05-02T09:00:00Z',
		body: 'You have a new comment on your confession. See what someone had to say!',
		avatar: 'https://example.com/avatars/comment.png',
	},
	{
		id: '4',
		title: 'Anonymous Like',
		date: '2024-05-02T15:00:00Z',
		body: 'Your confession received a new like. Someone appreciates your honesty!',
		avatar: 'https://example.com/avatars/like.png',
	},
	{
		id: '5',
		title: 'Daily Reflection Reminder',
		date: '2024-06-02T16:45:00Z',
		body: 'It’s time for your daily reflection. Share what’s on your mind today.',
		avatar: 'https://example.com/avatars/reflection.png',
	},
	{
		id: '6',
		title: 'Weekly Confession Digest',
		date: '2024-05-03T08:15:00Z',
		body: 'Here’s what you missed this week. Catch up on the most popular confessions.',
		avatar: 'https://example.com/avatars/digest.png',
	},
	{
		id: '7',
		title: 'Anonymous Message',
		date: '2024-06-30T2:00:00Z',
		body: 'You’ve received an anonymous message. Open it to see what someone wrote.',
		avatar: 'https://example.com/avatars/message.png',
	},
	{
		id: '8',
		title: 'Confession Featured',
		date: '2024-07-02T11:00:00Z',
		body: 'Congratulations! Your confession has been featured on the main page.',
		avatar: 'https://example.com/avatars/featured.png',
	},
	{
		id: '9',
		title: 'Report Status Update',
		date: '2024-07-03T8:45:00Z',
		body: 'Thank you for reporting. The issue has been reviewed and action has been taken.',
		avatar: 'https://example.com/avatars/report.png',
	},
	{
		id: '10',
		title: 'New Feature: Confession Tags',
		date: '2024-07-03T4:00:00Z',
		body: 'We’ve added a new feature! You can now tag your confessions to help others find them more easily.',
		avatar: 'https://example.com/avatars/new_feature.png',
	},
]
